### ISSUE TITLE
Support mysql without database?

### ISSUE THREAD

**Issue by lox** [betalo-sweden/await#19]
It seems like a database name is required for mysql polling, might it be possible to make that optional?

**Comment by djui** [comment]
Hi, you are correct, this is currently not possible. 

For me to add it: Could you state your order of preference, what criteria for an "available resource" in that case are sufficient:

1. The (TCP) port is open
2. Some de-facto tables or table content is available (any good suggestions?)
3. X?

**Comment by lox** [comment]
Basically just that mysql can be connected to and authenticated against with the provided credentials

**Comment by djui** [comment]
OK. Would the following hack work for you for now (until I make the database name optional):

    $ await -v mysql://root:secret@localhost:3306/information_schema

**Comment by lox** [comment]
Yup, thanks, much appreciated!
