### ISSUE TITLE
Specify hosts to await for in file.

### ISSUE THREAD

**Issue by adriancooney** [betalo-sweden/await#21]
Love this tool, thanks for the work. I'd love to be able to specify the hosts to wait for in a file. Doesn't have to be anything complicated, just read in each line. It'd be nice if we could incorporate env variables into it too. I'll try and take a look at this over the weekend and see what I can come up with. Any feedback on how it should be implemented?

**Comment by djui** [comment]
Hi Adrian! Thanks.

Could you define what a host is? e.g. If the resource is `localhost`, which protocol would a test is to verify the host is up? Ping?

Currently I am thinking about implementing this in two ways:

1. Add `-f` flag reading a newline separated file with resources.
2. Allow to pipe such a file's content via stdin

Would that work?

**Comment by djui** [comment]
Hi @adriancooney did you find some time to work on this?

Otherwise and if still desired, I will implement this.

**Comment by adriancooney** [comment]
Sorry @djui, I didn't even see you're first commend! My apologies. Unfortunately I didn't manage to get started on it because I ended up changing images in my compose file so the problem fixed itself. As for now, I don't have a use case for it anymore but thanks for the offer to build it!

**Comment by djui** [comment]
OK, great!

I will leave this open until I implemented and then close it.
