### ISSUE TITLE
Only show test errors after timeout expires?

### ISSUE THREAD

**Issue by lox** [betalo-sweden/await#22]
Currently the choices are either no output or very verbose messages about each test, which puts out a lot of output. It would be great to see just the last failure if it times out. Is there some middle ground between verbose and silent?

**Comment by djui** [comment]
Currently not possible, but sounds like a sane idea.

Any suggestion or preferences?

- Environment flag
- multiple `-vv` verbose levels,
- a different flag, `-x`
- or even changing the default

**Comment by djui** [comment]
I actually could see this behaviour as the default and then let verbose and quiet override it in either direction.

**Comment by lox** [comment]
Awesome! Thanks!
